### ISSUE TITLE
在tablayout切换页面到第3个就会出现如下错误

### ISSUE THREAD

**Issue by jackandroid2016** [simplepeng/StateAdapter#1]
![图片](https://user-images.githubusercontent.com/19246186/95733204-5aaf0c00-0cb4-11eb-9389-5b2df62fcb54.png)

![图片](https://user-images.githubusercontent.com/19246186/95733179-5256d100-0cb4-11eb-8006-6bd7f9e828bf.png)

**Comment by simplepeng** [comment]
你转成kotlin转出问题了，看样子就是类型转换错误呀。
`viewHolder as Nothing`这句

**Comment by jackandroid2016** [comment]
我转回来试试
